-- AlterTable
ALTER TABLE "Transaction" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "TransactionProduct" ALTER COLUMN "createdAt" SET DEFAULT CURRENT_TIMESTAMP;
